### ISSUE TITLE
Text-line detection

### ISSUE THREAD

**Issue by ghost** [WenmuZhou/PAN.pytorch#1]
@WenmuZhou @guochengzhen Hi there,
If I want to train a text-line detection model, what should be my configurations?

**Comment by WenmuZhou** [comment]
Currently the project is still under development

**Comment by ghost** [comment]
Hoping that this project keeps growing, by adding training documentation on how to train text-line detection & pretrained model.

keep-up the good work, Thank you

**Comment by WenmuZhou** [comment]
tks
