### ISSUE TITLE
Weights?

### ISSUE THREAD

**Issue by zobeirraisi** [WenmuZhou/PAN.pytorch#16]
Thanks for sharing the code,  is there any training weights available for this work?

**Comment by WenmuZhou** [comment]
Unable to upload model now for some reason

**Comment by ghost** [comment]
@WenmuZhou Upload the weights to [Google Drive](https://www.google.com/drive/), or [Microsoft OneDrive](https://onedrive.live.com)
I want to test your trained `resnet18+FPEM_FFM+pse` model

**Comment by WenmuZhou** [comment]
I will update model before 11.11

**Comment by WenmuZhou** [comment]
is't ok

**Comment by ghost** [comment]
@WenmuZhou 
The `resnet18+FPEM_FFM` that you uploaded, is it `1e-3` or `1e-4`?

**Comment by WenmuZhou** [comment]
1e-3
