### ISSUE TITLE
some problem about pse.cpp

### ISSUE THREAD

**Issue by ssxxx1a** [WenmuZhou/PAN.pytorch#26]
谢谢大佬的分享，有一些疑问就是，在predict测试的时候，（model用resnet18的，mac os上测试）提示以下错误，不知能否给些意见？ 0.0, best wishes!

```
pse.cpp:49:29: error: variable-sized object may not be initialized
        float kernel_vector[label_num][5] = {0};
                            ^~~~~~~~~
1 error generated.
make: *** [pse.so] Error 1
Traceback (most recent call last):
  File "/Users/abelleon/Documents/project/PAN.pytorch-master/predict.py", line 13, in <module>
    from post_processing import decode
  File "/Users/abelleon/Documents/project/PAN.pytorch-master/post_processing/__init__.py", line 17, in <module>
    raise RuntimeError('Cannot compile pse: {}'.format(BASE_DIR))
RuntimeError: Cannot compile pse: /Users/abelleon/Documents/project/PAN.pytorch-master/post_processing
```

**Comment by ssxxx1a** [comment]
在ubuntu 18上测试是可行，或许是mac和架构问题咯？

**Comment by mrwu-mac** [comment]
我遇到了同样的问题，请问你解决了吗

**Comment by ssxxx1a** [comment]
> 我遇到了同样的问题，请问你解决了吗

我直接放到ubuntu上了就没有该问题。。。

**Comment by mrwu-mac** [comment]
谢谢

**Comment by coldsummerday** [comment]
这个问题是macos 使用的是clang 编译器，不支持二维数组中第二维度为变量的数组初始化

**Comment by coldsummerday** [comment]
然后我把这个二维数组改为动态申请的形式：

float **kernel_vector;
        kernel_vector=(float**)malloc(label_num* sizeof(float*));
        for(int i = 0; i < label_num; i++)
        {
            *(kernel_vector+i) = (float *)malloc(sizeof(float)*5);//开辟列
        }

**Comment by coldsummerday** [comment]
然后我把这个二维数组改为动态申请的形式：

float kernel_vector;
kernel_vector=(float)malloc(label_num* sizeof(float*));
for(int i = 0; i < label_num; i++)
{
*(kernel_vector+i) = (float *)malloc(sizeof(float)*5);//开辟列
}

函数最后free掉：
 //释放kernel_vector
        for(int i = 0; i < label_num;i++)
		    free(*(kernel_vector+i));
