### ISSUE TITLE
Exception: ZIP entry not valid

### ISSUE THREAD

**Issue by mrwu-mac** [WenmuZhou/PAN.pytorch#28]
> /utils/cal_recall/rrc_evaluation_funcs.py", line 102, in load_folder_file
    raise Exception('ZIP entry not valid: %s' % name)
Exception: ZIP entry not valid: res_100104531.txt

验证和eval的时候都报这个错，请问这个是什么意思，我应该怎么解决呢？

**Comment by mrwu-mac** [comment]
> gt_img_([0-9]+).txt
100104533.txt
gt_img_([0-9]+).txt
100104531.txt
gt_img_([0-9]+).txt
100104530.txt
gt_img_([0-9]+).txt
100104532.txt
res_img_([0-9]+).txt
res_100104531.txt

这是我在re.match(fileNameRegExp, name)前print的

**Comment by yufanxin** [comment]
怎么解决的？

**Comment by 2443374695** [comment]
这个咋解决

**Comment by other-ones** [comment]
For those who still encounter this error, it occurs because of incorrect file naming. The img and gt should be in the form of "img_([0-9]+)" and "gt_img_([0-9]+)".
