### ISSUE TITLE
请问如何检测curved text呢？

### ISSUE THREAD

**Issue by mrwu-mac** [WenmuZhou/PAN.pytorch#29]

**Comment by Dany119** [comment]
期待它在CTW数据集上的表现

**Comment by mrwu-mac** [comment]
如果我想在ICDAR2019Art数据集上训练和测试

**Comment by Dany119** [comment]
@WenmuZhou 您好，请问您的pse_cpp输出的pred和https://github.com/whai362/PSENet中pse的输出有什么不同吗？我没学过c++，没能够看懂你们的pse，我想得到多边形而不是矩形的结果，希望能够得到您的帮助，谢谢！

**Comment by mrwu-mac** [comment]
@WenmuZhou  您好，请问您的pse_cpp输出的pred和https://github.com/whai362/PSENet 中pse的输出有什么不同吗？我没学过c++，没能够看懂你们的pse，我想得到多边形而不是矩形的结果，希望能够得到您的帮助，谢谢！

**Comment by WenmuZhou** [comment]
曲形文本需要改数据加载，我没加曲形的

**Comment by Dany119** [comment]
谢谢，我已经改了数据加载的部分，我想知道的是您decode函数里pse输出的pred的详细，我想修改decode来得到多边形的框
 
---原始邮件---
发件人: "zhoujun"<notifications@github.com&gt;
发送时间: 2020年3月5日 10:52:14
收件人: "WenmuZhou/PAN.pytorch"<PAN.pytorch@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Dany119"<840224946@qq.com&gt;;
主题: Re: [WenmuZhou/PAN.pytorch] 请问如何检测curved text呢？ (#29)



曲形文本需要改数据加载，我没加曲形的

**Comment by mrwu-mac** [comment]
非常感谢您的工作
