### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by cuimiao187561** [WenmuZhou/PAN.pytorch#7]
when i run predict.py

[shakey@xiaoi-778 PAN]$ python predict.py 
make: Entering directory `/opt/shakey/deep-learning/PAN/post_processing'
make: `pse.so' is up to date.
make: Leaving directory `/opt/shakey/deep-learning/PAN/post_processing'
self。gpu 1
ininstance True
torch.cuda.is True
self。gpu 1
ininstance True
torch.cuda.is True
device: cuda:0
Segmentation fault (core dumped)

**Comment by WenmuZhou** [comment]
update gcc
